/**
 *
 * $Id$
 */
package org.beezel.core.model.project.project.validation;

import org.beezel.core.model.project.project.Tag;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link org.beezel.core.model.project.project.Taggable}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TaggableValidator {
	boolean validate();

	boolean validateTags(EList<Tag> value);
}
